config/routes.rb
Rails.application.routes.draw do
  get '/' => "homes#index"
  get 'about' => "homes#about"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :posts
  resources :users

  #ダメなルート
  # get 'posts/index' => "posts#index"
  # get 'posts/edit' => "post#edit"
  # get "new" => "posts#new"
  # post "posts/create" => "posts#create"
  # get 'posts/:id' => "posts#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, {presence: true, length: {maximum: 20}}
	validates :content, {presence: true, length: {maximum: 100}}
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, {presence: true}
	validates :email, {presence: true, uniqueness: true}
	has_secure_password
	validates :password, {presence: true, length: { minimum: 6 }}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

	def authenticate_user
		if set_current_user == nil
			flash[:notice] = "ログインしてください"
			redirect_to "/login"
		end
	end

    def forbid_login_user
      if current_user
        flash[:notice] = "既にログインしています"
        redirect_to users_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_nparams)
  	if @post.save
  		flash[:notice] = "成功！！"
  		redirect_to("/posts")
  	else
  		render("posts/new")
  	end

  	# form_for用のcreate
  	# @post = Post.new(post_params)
  	# @post.save
  	# redirect_to("/post/index")
  end

  def edit
	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find_by(id: params[:id])
  	if @post.update(post_nparams)
  		flash[:notice] = "成功！"
  		redirect_to("/posts/#{@post.id}")
  	else
  		render :edit
  	end
  end

  def destroy
	@post = Post.find(params[:id])
	@post.destroy
	flash[:notice] = "削除！！"
	redirect_to posts_path
  end

  private
  	def post_nparams
  		params.permit(:title, :content)
  	end

  	#form_for用paramsのネスト
  	def post_params
  		params.require(:post).permit(:title, :content)
  	end

    def correct_user
      # if current_user.id != params[:id].to_i これはできない
      #   flash[:notice] = "権限なし"
      #   redirect_to "/users/index"
      post = Post.find(params[:id])
      if @current_user.id != post.user.id
        flash[:notice] = "権限なし"
        redirect_to users_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :forbid_login_user, {only: [:new, :create]}
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		flash[:notice] = "ログイン成功"
  		redirect_to "/users"
  	else
  		flash.now[:notice] = "間違いです"
  		render :new
  	end
  end

  def destroy
  	log_out
  	redirect_to("/")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :correct_user, {only: [:edit, :update]}
  def index
  	@users = User.all
  end

  def show
  	@user = User.find_by(id: params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_nparams)
    @user.image_name = "d_image.jpg"
  	if @user.save
      log_in(@user)
  		flash[:notice] = "登録！！"
  		redirect_to users_path
  	else
  		render :new
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])

    if image = params[:image]
      @user.image_name = "#{@user.id}.jpg" #jpgにしてる
      File.binwrite("public/#{@user.image_name}", image.read)
    end

  	if @user.update(user_nparams)
  		flash[:notice] = "成功！！！"
  		redirect_to users_path
  	else
  		render("/users/edit")
  	end
  end

	private

		def user_nparams
			params.permit(:name, :email, :image_name, :password, :password_confirmation)
		end

		def user_params
			params.require(:user).permit(:name, :email)
		end

    def correct_user
       # if current_user.id != params[:id].to_i これはできない
       #   flash[:notice] = "権限なし"
       #   redirect_to "/users/index"
       # end
       user = User.find(params[:id])
       if @current_user.id != user.id
         flash[:notice] = "権限なし"
         redirect_to users_path
       end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def set_current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def log_out
	  	session.delete(:user_id)
	  	@current_user = nil
	end

	def logged_in?
		!set_current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/index.html.erb
<h1>Topページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <div class="toppage">
    <%= link_to("TweetApp", "/") %>
  </div>
  <ul class="header-menus">
    <% if logged_in? %>
      <p>ようこそ</p>
      <%= @current_user.id %> <!-- どっちもいける同じようなものだから -->
      <%= set_current_user.name %>
      <li>
        <%= link_to("TweetAbout", about_path) %>
      </li>
      <li>
        <%= link_to("PostIndex", "/posts") %>
      </li>
      <li>
        <%= link_to("New", "/posts/new") %>
      </li>
      <li>
        <%= link_to("User一覧", "/users") %>
      </li>
      <li>
        <%= link_to("ログアウト", "logout", method: :delete) %>
      </li>
    <% else %>
      <li>
        <%= link_to("ログイン", "login",) %>
      </li>
      <li>
        <%= link_to("新規登録", new_user_path) %>
      </li>
    <% end %>
  </ul>
</header>
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>PostEditページ</h1>

<div>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |error| %>
			<%= error %>
		<% end %>
	<% end %>
</div>


<div>
	<%= form_tag(post_path, method: :patch) do %>
		<%= text_field_tag :title, @post.title %><br>
		<%= text_area_tag :content, @post.content %><br>
		<%= submit_tag("update") %>
	<% end %>
</div>

app/views/posts/index.html.erb
<p>PostIndexページ</p>
<div class="post_all">
	<% @posts.each do |post| %>
		<div class="post">
			<%= link_to("#{post.title}", "/posts/#{post.id}") %>
			<%= post.content %>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>PostNewページ</h1>
<div>
	<%= form_tag(posts_path, method: :post) do %>
		<%= text_field_tag :title, "title" %><br>
		<%= text_area_tag :content, "content" %><br>
		<%= submit_tag("create") %>
	<% end %>
</div>

<!-- 	form_for用（paramsはネスト）
  	<%= form_for(@post, url: {controller: 'posts', action: 'create' }) do |f| %>
		<%= f.text_field :title %><br>
		<%= f.text_area :content %><br>
		<%= f.submit %>
	<% end %>
 -->

app/views/posts/show.html.erb
<P>PostShowページ</P>
<div class="show">
	<p>
		<%= @post.title %>
	</p>
	<p>
		<%= @post.content %>
	</p>
	<!--<% if @post.user.id == current_user.id %> userモデルと紐付けてないからまだできない-->
		<p>
			<%= link_to("編集", edit_post_path) %>
		</p>
		<p>
			<%= link_to("削除", post_path(@post.id), method: :delete) %>
		</p>
	<!--<% end %> -->
</div>

<!-- なぜかrouteに使えない
"posts/#{@post.id}/edit" -->

app/views/users/edit.html.erb
<h1>UsersEdit</h1>

<div>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |error| %>
			<%= error %>
		<% end %>
	<% end %>
</div>


<div>
	<%= form_tag(user_path, method: :patch, multipart: true) do %>
		<%= image_tag "/#{@user.image_name}", :size =>'100x100' %><br>
		<%= file_field_tag :image %><br>
		<p>name</p><br>
		<%= text_field_tag :name, @user.name %><br>
		<p>email</p><br>
		<%= email_field_tag :email, @user.email %><br>
		<p>password</p><br>
		<%= password_field_tag :password, @user.password_digest %>
<!-- 		<p>password_confirmation</p>
		<%= password_field_tag :password_confirmation, @user.password_digest %> あってもなくてもできる-->
		<%= submit_tag("update") %>
	<% end %>
</div>

app/views/users/index.html.erb
<h1>UsersIndexページ</h1>
<div>
	<% @users.each do |user| %>
		<%= link_to("#{user.name}", "/users/#{user.id}") %><br>
	<% end %>
</div>

app/views/users/login_form.html.erb
<% if @error_message %>
    <%= @error_message %>
<% end %>

<%= form_tag("/login", method: :post) do %>
	<%= email_field_tag :email %><br>
	<%= password_field_tag :password %><br>
	<%= submit_tag("login") %>
<% end %>

app/views/users/new.html.erb
<h1>UsersNewページ</h1>

<div>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |error| %>
			<%= error %>
		<% end %>
	<% end %>
</div>


<div>
	<%= form_tag(users_path, method: :post) do %>
		<P>name</P><br>
		<%= text_field_tag :name, @user.name %><br>
		<p>email</p><br>
		<%= email_field_tag :email, @user.email %><br>
		<p>password</p><br>
		<%= password_field_tag :password %>
		<p>password_confirmation</p>
		<%= password_field_tag :password_confirmation %>
		<%= submit_tag("create") %>
	<% end %>

</div>

app/views/users/show.html.erb
<h1>UsersShowページ</h1>

<%= image_tag "/#{@user.image_name}", :size =>'100x100' %><br>
<%= @user.name %><br>
<%= @user.email %><br>
<% if @user.id == @current_user.id %>
	<%= link_to("編集", edit_user_path(@user.id)) %>
<% end %>